[project]
name = "extend-quantity"
version = "0.1.0"
dependencies = ["si_units>=0.9.0"]
readme = "README.md"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
bindings = "pyo3"
manifest-path = "extend_quantity/Cargo.toml"
