[package]
name = "quantity"
version = "0.3.2"
authors = ["Philipp Rehner <prehner@ethz.ch>",
           "Gernot Bauer <bauer@itt.uni-stuttgart.de>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Representation of quantites, i.e. of unit valued scalars and arrays."
homepage = "https://github.com/itt-ustutt/quantity"
readme = "README.md"
repository = "https://github.com/itt-ustutt/quantity"
keywords = ["physics", "units", "SI"]
categories = ["data-structures", "science"]
exclude = ["/.github/*", "*.ipynb", "/docs"]

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "./src/docs-header.html" ]

[dependencies]
ndarray = { version = "0.15", features = ["serde", "approx"] }
approx = "0.4"
lazy_static = "1.4"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
ang = "0.5"
regex = "1.5"
ndarray-linalg = { version = "0.14", optional = true }
numpy = { version = "0.14", optional = true }

[dependencies.pyo3]
version = "0.14"
features = ["multiple-pymethods"]
optional = true

[features]
default = []
python = ["pyo3", "numpy"]
linalg = ["ndarray-linalg"]
openblas-system = ["ndarray-linalg/openblas-system"]
openblas-static = ["ndarray-linalg/openblas-static"]
intel-mkl-system = ["ndarray-linalg/intel-mkl-system"]
intel-mkl-static = ["ndarray-linalg/intel-mkl-static"]
netlib-system = ["ndarray-linalg/netlib-system"]
netlib-static = ["ndarray-linalg/netlib-static"]
