[package]
name = "quantity"
version = "0.1.1"
authors = ["Philipp Rehner <rehner@itt.uni-stuttgart.de>",
           "Gernot Bauer <bauer@itt.uni-stuttgart.de>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Representation of quantites, i.e. of unit valued scalars and arrays."
homepage = "https://github.com/itt-ustutt/quantity"
repository = "https://github.com/itt-ustutt/quantity"
keywords = ["physics", "units", "SI"]
categories = ["data-structures", "science"]
exclude = ["/.github/*", "*.ipynb", "/docs"]

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "./src/docs-header.html" ]

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
ndarray = { version = "0.14", features = ["serde", "approx"] }
approx = "0.4"
lazy_static = "1.4"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
ang = "0.4"
regex = "1.0"
ndarray-linalg = { version = "0.13", optional = true }
numpy = { version = "=0.13.0", optional = true }

[dependencies.pyo3]
version = "0.13"
features = ["extension-module", "abi3", "abi3-py36"]
optional = true

[features]
default = []
python = ["pyo3", "numpy"]
linalg = ["ndarray-linalg"]
openblas-system = ["ndarray-linalg/openblas-system"]
openblas-static = ["ndarray-linalg/openblas-static"]
intel-mkl-system = ["ndarray-linalg/intel-mkl-system"]
intel-mkl-static = ["ndarray-linalg/intel-mkl-static"]
netlib-system = ["ndarray-linalg/netlib-system"]
netlib-static = ["ndarray-linalg/netlib-static"]
