name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: ["", "ndarray", "approx", "ndarray approx", "python", "python_numpy", "num-dual"]

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: Run tests
        run: cargo test --release
