name: Test Documentation

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install python dependencies
        run: |
          pip install sphinx sphinx-rtd-theme numpydocs numpy
      - name: Build wheels
        uses: messense/maturin-action@v1
        with:
          manylinux: auto
          command: build
          args: --release --out dist --no-sdist --cargo-extra-args="--features python"
      - name: Install module
        run: |
          pip install quantity --no-index --find-links dist --force-reinstall
      - name: Run doctests
        run: sphinx-build docs/ public/ -b doctest
