name: Test Python extension package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    defaults:
      run:
        working-directory: ./app

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install python dependencies
        run: pip install numpy pytest
      - name: Build wheels
        uses: messense/maturin-action@v1
        with:
          working-directory: ./example
          manylinux: auto
          command: develop
          args: --release
      - name: Test with pytest
        working-directory: ./example
        run: pytest --doctest-modules
