name: Test Python extension package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install python dependencies
        run: pip install numpy pytest maturin
      - name: Build wheels for extend-quantity
        working-directory: ./example/extend_quantity
        run: |
          maturin build --release --out dist
          pip install extend_quantity --no-index --find-links dist --force-reinstall
      - name: Build wheels for si-units
        run: |
          maturin build --release --out dist
          pip install si-units --no-index --find-links dist --force-reinstall
      - name: Test with pytest
        working-directory: ./example
        run: pytest --doctest-modules
